# Remote Hosts - comma delimited
remote_hosts=${jmeter-remote-hosts}

# RMI port to be used by the server (must start rmiregistry with same port)
server_port=${jmeter-port}

# Parameter that controls the RMI port used by the RemoteSampleListenerImpl (The Controler)
# Default value is 0 which means port is randomly assigned
# You may need to open Firewall port on the Controller machine
client.rmi.localport=${client-port}

# To change the default port (1099) used to access the server:
server.rmi.port=${jmeter-port}

# To use a specific port for the JMeter server engine, define
# the following property before starting the server:
server.rmi.localport=${jmeter-port}

# Disable SSL for RMI
server.rmi.ssl.disable=true

server.exitaftertest=false

# Sample sender configuration:
# - true (default) means client configuration will be used
# - false means server configuration will be used
#
# For further information: https://jmeter.apache.org/usermanual/remote-test.html#sendermode
sample_sender_client_configured=false
mode=StrippedBatch
#mode=Asynch

# Report generator temporary directory
jmeter.reportgenerator.temp_dir=/tmp