# RMI port to be used by the server (must start rmiregistry with same port)
server_port=${jmeter-port}

# To change the default port (1099) used to access the server:
server.rmi.port=${jmeter-port}

# To use a specific port for the JMeter server engine, define
# the following property before starting the server:
server.rmi.localport=${jmeter-port}

# Disable SSL for RMI
server.rmi.ssl.disable=true

server.exitaftertest=false

httpsampler.ignore_failed_embedded_resources=true